os: linux
dist: focal

language: go

go:
- 1.13

env:
- GO111MODULE="on"

before_install:
  - sudo apt-get update
  - sudo apt-get --yes install libgit2-dev git

install:
- go mod download

script:
- go test ./...