os: linux
dist: focal

language: go

go:
- 1.13

env:
- GO111MODULE="on"

before_install:
  - sudo apt-get update
  - sudo apt-get --yes install libgit2-dev git

install:
- go mod download

script:
- go test ./...
- go build
- git clone https://github.com/JetBrains/intellij-community.git
- cd intellij-community
- git gc
- ../git-fast-reword -date-optimization 5d2dfa41c046ce288f1aaddb243aa364aef043db "New message"
